<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.2.0 Beta 1 (32000) on Tue, 21 Jun 2011 21:35:53 +0000 by Edgar_94_
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'enter_username'				=> "Username",
'enter_useremail'				=> "Email Address",
'logout_complete'				=> "Log out complete",
'enter_name_and_email'				=> "Username / Email",
'ipb_login'				=> "IP.Board: Log in",
'bad_email_password'				=> "Your login credentials were not valid",
'no_acp_access'				=> "You do not have permission to access the ACP",
 ); 
