<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.2.0 Beta 1 (32000) on Tue, 21 Jun 2011 21:35:53 +0000 by Edgar_94_
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'label_notify'				=> "Receive notification",
'likeadded'				=> "Added:",
'freq_daily'				=> "Daily",
'freq_weekly'				=> "Weekly",
'label_anon'				=> "%s Anonymously",
'label_anon_desc'				=> "Do not show me in the summary",
'freq_immediate'				=> "Instantly",
'freq_offline'				=> "Only when not online",
'label_freq'				=> "Frequency",
'likedby'				=> "Followed By",
'fave_title'				=> "%s",
 ); 
