<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.2.0 Beta 1 (32000) on Tue, 21 Jun 2011 21:35:53 +0000 by Edgar_94_
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'email_recepient'				=> "Recipient",
'email_friend'				=> "Use this feature to let a friend know about this topic!",
'email_details'				=> "Enter the email details",
'email_sent_txt'				=> "Thanks, the email has been successfully sent to",
'msg_txt'				=> "Note: By using this form, the recipient will be able to view your email address",
'member_address_title'				=> "Members Email Address",
'send_email_to'				=> "Send an email to",
'show_address_text'				=> "You can send this member an email by clicking on the link below. IP.Board does not show email addresses in the topic view to prevent email addresses being harvested by 'spam bots'.",
'title'				=> "Send a page to a friend",
'message'				=> "Message",
'subject'				=> "Subject",
'redirect'				=> "The email has been sent",
'submit_send'				=> "Send Email",
'to_email'				=> "Send to (Email Address)",
'to_name'				=> "Send to (Person's Name)",
'email_sent'				=> "The email has been sent",
'send_lang'				=> "Send this email in",
'gen_error'				=> "You are not logged in or able to send emails",
'no_message'				=> "You must enter some content for the email",
'exceeded_flood'				=> "The mail could not be sent because you have already sent an email within the last %s minutes",
'exceeded_quota'				=> "The mail could not be sent because you have exceeded your allotted quota of %s emails a day",
'imp_text'				=> "IMPORTANT: To prevent malicious use, all emails sent via this form are logged and the contents recorded and available to the administrators. DO NOT email user names, passwords or any personal details.",
'emailing_prefix'				=> "Emailing",
'forum_langbit'				=> "Forum",
'topic_langbit'				=> "Topic",
'email_member'				=> "Email Member",
'no_subject'				=> "You must enter a subject for the email",
'tweet_ok'				=> "Your tweet was successful!",
'twitter_chrs_left'				=> "chars left. Shortened URL will be auto-added",
'twitter_share'				=> "Share",
'share_via_twitter'				=> "Share Via Twitter",
'share_via_facebook'				=> "Share Via Facebook",
'facebook_share'				=> "Share",
'fbc_comment_desc'				=> "You can optionally leave a comment below",
'facebook_post_ok'				=> "The link was posted successfully",
'share_fb_name'				=> "Logged into Facebook as",
'fb_share_default'				=> "Share link with your own comment...",
'err_reg_code'				=> "The Captcha input was incorrect. Please try again.",
 ); 
