<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.2.0 Beta 1 (32000) on Tue, 21 Jun 2011 21:35:53 +0000 by Edgar_94_
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'label_anon'				=> "Set Favorite Anonymously",
'label_notify'				=> "Receive notification of %s",
'fave_title'				=> "Set as favorite",
'label_freq'				=> "Frequency",
'label_anon_desc'				=> "Do not show me in favorites list",
'freq_immediate'				=> "Instantly",
'freq_offline'				=> "Only when not online",
'freq_weekly'				=> "Weekly",
'freq_daily'				=> "Daily",
 ); 
