<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.2.0 Beta 1 (32000) on Tue, 21 Jun 2011 21:35:53 +0000 by Edgar_94_
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'view_it_anyway'				=> "View it anyway?",
'permalink'				=> "Permalink:",
'comment_reply'				=> "Quote",
'reply_to_comment'				=> "Reply directly to this comment",
'mq_image_add'				=> "MultiQuote",
'comment_notice_subject'				=> "A new comment has been left on <a href='%s'>%s</a>",
'report_link'				=> "Report",
'comment_notifications'				=> "<#NAME#>,

<#AUTHOR#> has just commented on \"<#TITLE#>\".

<#COMMENT#>

You can review the new comment here:
<#URL#>",
'comment_button_post'				=> "Add Comment",
'check_all'				=> "Check all",
'view_comment'				=> "View comment",
'ignored_comments_not'				=> "This comment is hidden because you have chosen to ignore posts by",
'comments_header'				=> "Comments",
'delete_comment'				=> "Delete comment",
'delete_link'				=> "Delete",
'edit_link'				=> "Edit",
'comments_act_go'				=> "Go",
'edit_comment'				=> "Editing comment from:",
'comment_save'				=> "Save",
'unapprove_x_comments'				=> "Un-approve",
'delete_x_comments'				=> "Delete",
'approve_x_comments'				=> "Approve",
'manage_comments_pop'				=> "Manage Comments",
'comment_action_count'				=> "With <span id='comment_count'>#{count}</span> checked comments:",
'comm_confirm_delete_desc'				=> "Are you sure you want to delete this comment?",
'del_comm_now'				=> "Delete comment now",
'comm_confirm_delete'				=> "Confirm Delete",
'comment_permalink'				=> "Get the permalink",
'comment_approval_required'				=> "Your comment requires moderator approval before it will be shown.",
 ); 
