<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.2.0 Beta 1 (32000) on Tue, 21 Jun 2011 21:35:53 +0000 by Edgar_94_
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'help_return_list'				=> "Return to the list of topics",
'help_back_list_title'				=> "Back to list",
'help_read_document'				=> "Read document",
'page_title'				=> "View Help Topics",
'help_topic'				=> "Help Topic",
'help_topics'				=> "Help Topics",
'help_txt'				=> "Choose a topic from the list, or search for a topic",
'choose_file'				=> "Choose a Topic",
'topic_text'				=> "Here is the topic you chose to view",
'no_help_topics'				=> "There are no help topics yet",
 ); 
