<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.2.0 Beta 1 (32000) on Tue, 21 Jun 2011 21:35:53 +0000 by Edgar_94_
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'o_word_title'				=> "Download Microsoft Word Version",
'o_word_desc'				=> "This will enable you to download a version of this topic in an editable Word format. This will open your browser's download dialogue box",
'back_topic'				=> "Back to the topic",
'o_html_title'				=> "Download HTML Version",
'o_html_desc'				=> "This will enable you to download a HTML version of this topic to your hard drive. This will open your browser's download dialogue box",
'o_print_title'				=> "Printer Friendly Version",
'o_print_desc'				=> "This will display the topic in a simple, printer friendly format on this page, no download is required.",
'tvo_title'				=> "Topic View Options for:",
'topic'				=> "Topic",
'start'				=> "started by",
'by'				=> "Posted by",
'title'				=> "Printable Version of Topic",
'on	'				=> "on",
'forum'				=> "Forum",
'end'				=> "end",
'powered_by'				=> "Powered by ",
'posted_prefix'				=> "Posted",
'click_toview'				=> "Click to view Topic",
'please_choose'				=> "Please choose an option below",
'view_original'				=> "(View original topic)",
 ); 
