<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.2.0 Beta 1 (32000) on Tue, 21 Jun 2011 21:35:53 +0000 by Edgar_94_
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'topic_noperms'				=> "You do not have permission to access this forum",
'topic_noattach'				=> "The specified topic does not have any attachments",
'go_button'				=> "Go",
'who_replied_title'				=> "Who posted in this topic",
'stats_missing_tid'				=> "You must select a valid topic for this feature",
'notopic_attach'				=> "Could not load attachments for the requested topic",
'leader_all_forums'				=> "All Forums",
'leader_forums'				=> "Forums",
'leader_location'				=> "Location",
'leader_name'				=> "Member Name",
'leader_mods'				=> "Forum Moderators",
'forum_leaders'				=> "The moderating team",
'leader_global'				=> "Global Moderators",
'leader_admins'				=> "Administrators",
'member_today'				=> "Posts Today",
'member_joined'				=> "Joined",
'member_percent'				=> "% of today's posts",
'no_info'				=> "No information is available at this time",
'top_poster_title'				=> "Today's top 20 posters",
'member_posts'				=> "Total Member Posts",
'member'				=> "Member",
'todays_posters'				=> "Today's Top 20 Posters",
'goto_profile'				=> "Go to profile",
'whoposted_posts'				=> "Posts",
'whoposted_name'				=> "Member name",
'who_farted'				=> "Who posted in:",
'no_forums'				=> "View Forums (%s total...)",
 ); 
