<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.2.0 Beta 1 (32000) on Tue, 21 Jun 2011 21:35:53 +0000 by Edgar_94_
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'mem_change_button'				=> "Change...",
'm_overrride'				=> "Override group permission masks with...",
'mem_posts'				=> "Posts",
 ); 
