<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.2.0 Beta 1 (32000) on Tue, 21 Jun 2011 21:35:53 +0000 by Edgar_94_
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'emo_title'				=> "Emoticons",
'bbc_before'				=> "You Type",
'bbc_after'				=> "We Show",
'bbc_intro'				=> "BB Code is a quick and easy way to add effects or formatting to your posts.<br />It is used in a similar format to HTML tags which you may already be familiar with.<br />Below is a quick guide to the most common BB Code uses.",
'bbc_title'				=> "BB Code",
 ); 
