<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.2.0 Beta 1 (32000) on Tue, 21 Jun 2011 21:35:53 +0000 by Edgar_94_
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'b_deleted'				=> "Bulk mail deleted!",
'b_nobulk'				=> "No bulk mailings to display",
'b_create'				=> "Create new bulk mail",
'b_deletedot'				=> "Delete...",
'b_editdot'				=> "Edit...",
'b_resenddot'				=> "Resend...",
'b_cancel'				=> "Cancel",
'b_cancelconfirm'				=> "Click OK to cancel this mail",
'b_inprogress'				=> "Sending mail in progress",
'b_notyet'				=> "Not yet sent",
'b_minutes'				=> " minutes",
'b_lsentto'				=> "Sent To",
'b_ltime'				=> "Time Taken",
'b_lsubject'				=> "Subject",
'b_lsenton'				=> "Sent On",
'b_stored'				=> "Your stored bulk mail",
'b_qposts'				=> "<em>The number of posts for the mail recipient</em>",
'b_qjoin'				=> "<em>The join date of the mail recipient</em>",
'b_qmname'				=> "<em>The member name of the mail recipient</em>",
'b_qid'				=> "<em>The member ID of the mail recipient</em>",
'b_qonlinetime'				=> "<em>The time that the most number of members were online</em>",
'b_qptotal'				=> "<em>The total number of posts</em>",
'b_qonline'				=> "<em>The most number of users online</em>",
'b_qmtotal'				=> "<em>The total number of registered members</em>",
'b_ndays'				=> "Send to members whose last visit was <em><strong>n</strong></em> days ago",
'b_njoined'				=> "Send to members who joined <em><strong>n</strong></em> days ago",
'b_leaveblank'				=> "Leave blank to not filter",
'b_preview'				=> "Preview",
'b_qtag'				=> "Quick Tags",
'b_qtag_info'				=> "You may use the following 'quick tags' in your mail and they will be converted when the mail is sent.",
'b_qbname'				=> "<em>The name of your community</em>",
'b_qboardurl'				=> "<em>The URL to your community</em>",
'b_nposts'				=> "Send to members with <em><strong>n</strong></em> posts",
'b_groups'				=> "<strong>Send to Groups:</strong>",
'b_addfilters'				=> "<strong>Additional Filters</strong>",
'b_honor'				=> "Honor the '<strong>Send me any updates seny by the community administrator</strong>' setting? This will only mail members who have opted in.",
'b_step2'				=> "Step 2: Filters",
'b_html'				=> "Send mail in HTML format? (Full HTML formatting &amp; and tags allowed)",
'b_options'				=> "Options",
'b_content'				=> "<strong>Mail Content</strong>",
'b_subject'				=> "<strong>Mail Subject</strong>",
'b_edit'				=> "Edit Mail",
'b_editstored'				=> "Editing Stored Mail",
'b_proceed'				=> "Proceed...",
'b_morethan'				=> "more than",
'b_lessthan'				=> "less than",
'b_step1'				=> "Step 1: Start New Bulk Mail",
'b_step1_title'				=> "Mail Details",
'b_mailbutton'				=> "Start Sending The Mail",
'b_percycle'				=> "<strong>Number sent per cycle</strong>",
'b_maillogedit'				=> "Bulk mail ( %s ) edited",
'b_edited'				=> "Bulk mail edited!",
'b_mailcontents'				=> "{member_name},



-------------------------------------
{board_name} Statistics:
-------------------------------------
Registered Users: {reg_total}
Total Posts: {total_posts}
Busiest Time: {busy_count} users were online on {busy_time}

-------------------------------------
Handy Links
-------------------------------------
Community Address: {board_url}
Log In: {board_url}?app=core&module=global&section=login
Lost Password Recovery: {board_url}?app=core&module=global&section=lostpass

-------------------------------------
How to unsubscribe
-------------------------------------
Visit your email preferences ({board_url}?app=core&module=usercp) and ensure that the box for 'Send me any updates sent by the community administrator' is unchecked and submit the form",
'b_sending'				=> "<strong>Sending the Mail</strong>",
'b_sending_info'				=> "Clicking the 'Start Sending The Mail' button below will activate the task manager's send bulk mail function which will send the mail in batches until the all the mail has been sent. You can watch the progress from the main Bulk Mail screen and cancel the mail from being sent.<br />We strongly recommend that you opt to send 20 mails per cycle as a maximum. Any more per cycle could severly affect performance of your server while the mail is being sent out.<br /><br />As the mail is sent out in cycles of <em><b>n</b></em> &nbsp;per minute, it can take a while to process all the mail.",
'b_editmail'				=> "Edit This Mail",
'b_maildetails'				=> "<strong>Mail Details</strong>",
'b_countmember'				=> "Sending the bulk mail to <strong>%s</strong> members",
'b_maillogadd'				=> "Bulk mail ( %s ) added",
'b_nonefound'				=> "Your criteria didn't match any members. Please adjust your current criteria, ensuring all correct fields are selected or entered.",
'b_nogroups'				=> "You must select at least one group to send this mail message to. Please try again.",
'b_norecord'				=> "Could not find the bulk mail record you requested. Please try again.",
'b_nosend'				=> "Cannot send - the mail doesn't have a subject and content. Please try again.",
'b_initiated'				=> "Bulk mail initiated!",
'b_noid'				=> "There was no ID passed to the mailer. Please try again.",
'b_entercont'				=> "You must enter a mail subject and mail content before submitting. Please try again.",
'bulkmail_notes_info'				=> "Please be aware that bulk emails are sent by a task in IP.Board in the System Scheduler.  They are not sent immediately upon saving or resending a bulk email.  You can manually run this task in the System Scheduler if you wish to force emails to send immediately, otherwise
							they will be sent based on activity on your forums.  Also, please be aware that any users who elect <em>not</em> to receive emails from the administrator in their user control panel will <strong>not</strong> receive bulk mails.",
'b_canceled'				=> "Bulk mail canceled!",
'b_title'				=> "Bulk Mail Management",
'bulkmail_notes_tl'				=> "Important Information",
 ); 
